apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-autoscaling-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-autoscaling-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Target 50% CPU - scale up when above, scale down when below
        averageUtilization: 50
  behavior:
    scaleDown:
      # Wait 30 seconds before scaling down to avoid rapid fluctuations
      stabilizationWindowSeconds: 30
      policies:
      # Scale down by at least 2 pods every 30 seconds
      - type: Pods
        value: 2
        periodSeconds: 30
      # Scale down by up to 25% every 30 seconds (increased from 10%)
      - type: Percent
        value: 25
        periodSeconds: 30
      # Use the larger of the two policies (more conservative)
      selectPolicy: Max
    scaleUp:
      # Scale up immediately when CPU is high (no stabilization delay)
      stabilizationWindowSeconds: 0
      policies:
      # Scale up aggressively: double every 15 seconds if needed
      - type: Percent
        value: 100
        periodSeconds: 15
      # Or add at least 2 pods every 15 seconds
      - type: Pods
        value: 2
        periodSeconds: 15
      # Use the larger of the two policies (more aggressive)
      selectPolicy: Max
