---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-autoscaling-app
  labels:
    app: k8s-autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-autoscaling
  template:
    metadata:
      labels:
        app: k8s-autoscaling
    spec:
      serviceAccountName: dashboard-sa
      containers:
      - name: app
        image: adamabd97/k8s-autoscaling-demo:latest
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-autoscaling-service
  labels:
    app: k8s-autoscaling
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: k8s-autoscaling
